export const APP_INIT = 'APP_INIT';
export const APP_INIT_FINISHED = 'APP_INIT_FINISHED';
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCES = 'SEND_MESSAGE_SUCCES';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
